[workspace]
members = [
    "rafos-console",
    "rafos-syscall",
    "rafos-macros",
    "rafos-tests",
    "rafos-executor",
    "rafos-libs/rafos-runtime",
    "rafos-libs/rafos-heap",
]
resolver = "1"

# [profile.release]
# opt-level = 1