[package]
name = "rafos-vfs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.1"
numeric-enum-macro = "0.2.0"
spin = "0.9"

errno = {path = "../rafos-errno", package = "rafos-errno"}
kernel-sync = {  git = "https://github.com/tkf2019/kernel-sync" }