[build]
target = "riscv64gc-unknown-linux-gnu"
target-dir = "../target"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-unknown-linux-gnu-gcc"
rustflags = ["-Clink-args=-fpie -nostartfiles -Tlinker.ld"]