[build]
target = "riscv64gc-unknown-linux-gnu"
target-dir = "../target"
# relocation-model = "static"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-unknown-linux-gnu-gcc"
rustflags = ["-Clink-args=-static -nostartfiles -Bstatic -l:libc.a -Tlinker.ld"]